name: AWS CDK Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

concurrency: server-cdk-deploy

jobs:
  cdk-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Install client dependencies
        working-directory: ./client
        run: npm ci

      - name: Build Client
        working-directory: ./client
        run: npx vite build --mode demo

      - name: Install server dependencies
        working-directory: ./server
        run: npm ci

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::316516756945:role/github-ci
          role-session-name: main-branch-deploy

      - name: CDK Deploy
        run: npx cdk deploy --all -c stage=demo --require-approval never
