name: Client PR Review

on:
  pull-request:
    paths:
      - "client/**"

concurrecny: client-pr

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Build
        working-directory: ./client
        run: npm run build
